import assert from "node:assert/strict";
import { matchesTracomaGeography, tracomaCount, tracomaPositivity, validateTracomaFilters } from "@/lib/tracoma-data";
import { aggregateTracomaOverview, normalizeSinanTracomaRow, parseTracomaQuestion } from "@/services/sinan-tracoma";
import { aggregateSinanTracomaRates } from "@/services/population-rates";
import { listarMunicipiosPorGve } from "@/lib/municipios-sp";

for (const invalid of [null, undefined, "", " ", "abc", -1, "-2", "1.5", 2.3, true, Infinity]) assert.equal(tracomaCount(invalid), null);
assert.equal(tracomaCount("1.234"), 1234);
assert.equal(tracomaCount("12,0"), 12);
assert.equal(tracomaCount(0), 0);
assert.equal(tracomaPositivity(101, 100), null);
assert.equal(tracomaPositivity(0, 100), 0);
assert.equal(tracomaPositivity(null, 100), null);
assert.equal(tracomaPositivity(0, 0), null);
assert.throws(() => validateTracomaFilters({ yearStart: 2025, yearEnd: 2024 }));
assert.throws(() => validateTracomaFilters({ yearStart: "2024.5" }));
assert.throws(() => validateTracomaFilters({ yearEnd: "not-a-year" }));
assert.throws(() => validateTracomaFilters({ yearEnd: new Date().getFullYear() + 1 }));
assert.equal(matchesTracomaGeography({ municipio: "3550308", gve: "INCORRETO" }, { municipio: "São Paulo", gve: "SAO PAULO" }), true);
assert.equal(matchesTracomaGeography({ municipio: "Sao Paulo" }, { municipio: "355030" }), true);
assert.equal(matchesTracomaGeography({ municipio: "Sao Paulo" }, { municipio: "Sao" }), false);
assert.equal(parseTracomaQuestion("Total de casos por município no NOTTRACONET").bank, "nottraconet");
assert.equal(parseTracomaQuestion("Registros individuais por GVE no TRACONET ano passado").yearStart, new Date().getFullYear() - 1);
assert.equal(parseTracomaQuestion("Casos no TRACONET este ano").yearEnd, new Date().getFullYear());

const tc = [{ source_bank: "traconet", ano: 2024, municipio: "355030", raw: { FORMA_TF: 1, FORMA_TI: 1 } }];
const consolidated = (raw: Record<string, unknown>, ano = 2024, municipio = "355030") => ({ source_bank: "nottraconet", ano, municipio, raw });
const overview = aggregateTracomaOverview(tc, [consolidated({ NU_CASOPOS: 10, NU_CASOEXA: 100, NU_TF: 10 })]);
assert.equal(overview.byYear[0].tf, 1, "Forms cannot sum individual and consolidated banks");
assert.equal(overview.byYear[0].ti, 1);
assert.equal(overview.positividade, 10);
assert.equal(aggregateTracomaOverview(tc, []).totalExaminados, null, "Absent consolidated bank is unknown");
assert.equal(aggregateTracomaOverview(tc, [consolidated({ NU_CASOEXA: 100 })]).totalPositivos, null);
const dilutedInvalid = [consolidated({ NU_CASOPOS: 101, NU_CASOEXA: 100 }), consolidated({ NU_CASOPOS: 0, NU_CASOEXA: 1000 })];
assert.equal(aggregateTracomaOverview(tc, dilutedInvalid).positividade, null, "Invalid report must not be diluted by aggregation");
assert.equal(aggregateTracomaOverview(tc, [consolidated({ NU_CASOPOS: 10, NU_ALUNOS: 100 })]).totalExaminados, null, "Ambiguous student totals cannot become examined denominators");

const population = (codigo_ibge: string, ano = 2024, populacao = 1000) => ({ codigo_ibge, ano, populacao, municipio: codigo_ibge, uf: "SP" });
const rates = aggregateSinanTracomaRates([consolidated({ CASOPOS: 10, CASOEXA: 100 })], [population("3550308")], { municipio: "São Paulo", yearStart: 2024, yearEnd: 2024 });
assert.equal(rates.byMunicipality[0].prevalencia, 10);
assert.equal(rates.byMunicipality[0].taxaDeteccao100k, 1000);
assert.equal(rates.populationYear, 2024);
const missingPopulation = aggregateSinanTracomaRates([consolidated({ NU_CASOPOS: 0, NU_CASOEXA: 100 })], [], { municipio: "São Paulo" });
assert.equal(missingPopulation.byMunicipality[0].prevalencia, 0);
assert.equal(missingPopulation.byMunicipality[0].taxaDeteccao100k, null);
const missingCount = aggregateSinanTracomaRates([consolidated({ NU_CASOEXA: 100 })], [population("355030")]);
assert.equal(missingCount.byMunicipality[0].positivos, null);
assert.equal(missingCount.byMunicipality[0].prevalencia, null);
assert.equal(aggregateSinanTracomaRates(dilutedInvalid, [population("355030")]).byMunicipality[0].prevalencia, null);
const gap = aggregateSinanTracomaRates([consolidated({ NU_CASOPOS: 10, NU_CASOEXA: 100 })], [population("355030")], { municipio: "São Paulo", yearStart: 2023, yearEnd: 2024 });
assert.deepEqual(gap.byMunicipality[0].missingYears, [2023]);
assert.equal(gap.byMunicipality[0].taxaDeteccao100k, null);
assert.equal(gap.byGve[0].taxaDeteccao100k, null);
const municipalities = listarMunicipiosPorGve("CAMPINAS");
const fullPopulation = municipalities.map((municipality) => population(municipality.codigo));
const gveRate = aggregateSinanTracomaRates([consolidated({ NU_CASOPOS: 10, NU_CASOEXA: 100 }, 2024, municipalities[0].codigo)], fullPopulation, { gve: "CAMPINAS" });
assert.equal(gveRate.byGve[0].populacao, municipalities.length * 1000, "GVE denominator must include municipalities without reports");
assert.equal(gveRate.byGve[0].reportedMunicipalities, 1);
assert.equal(gveRate.byGve[0].territoryMunicipalities, municipalities.length);
assert.equal(gveRate.byGve[0].taxaDeteccao100k, Number((10 / (municipalities.length * 1000) * 100000).toFixed(2)));
assert.equal(aggregateSinanTracomaRates([], fullPopulation).byMunicipality.length, 0, "No reports cannot generate fake zero rows");

const longRow = { NU_NOTIFIC: "1", padding: "a".repeat(600), FORMA_TF: 1 };
assert.notEqual(normalizeSinanTracomaRow(longRow, "traconet").row_key, normalizeSinanTracomaRow({ ...longRow, FORMA_TF: 2 }, "traconet").row_key, "Late raw fields must affect the import key");
assert.equal(normalizeSinanTracomaRow({ ANO: 2024, NU_NOTIFIC: "1" }, "traconet").row_key, normalizeSinanTracomaRow({ NU_NOTIFIC: "1", ANO: 2024 }, "traconet").row_key, "Key order must not duplicate identical rows");
console.log("tracoma reliability tests passed");
