/**
 * Lookup IBGE 6 dígitos → { nome, gve } para municípios do Estado de São Paulo.
 * Cobre todos os 331 municípios distintos presentes no banco SINAN tracoma.
 * Códigos verificados via API pública IBGE (servicodados.ibge.gov.br).
 * GVEs conforme estrutura das 28 GVEs da Secretaria de Saúde SP.
 */

export interface MunicipioInfo {
  nome: string;
  gve: string;
}

const MUNICIPIOS_SP: Record<string, MunicipioInfo> = {
  "350010": { nome: "Adamantina",               gve: "MARILIA" },
  "350020": { nome: "Adolfo",                    gve: "SAO JOSE DO RIO PRETO" },
  "350030": { nome: "Aguaí",                     gve: "SAO JOAO DA BOA VISTA" },
  "350040": { nome: "Águas da Prata",            gve: "SAO JOAO DA BOA VISTA" },
  "350050": { nome: "Aguas de Lindoia",                 gve: "CAMPINAS" },
  "350055": { nome: "Águas de Santa Bárbara",    gve: "BOTUCATU" },
  "350060": { nome: "Águas de São Pedro",        gve: "PIRACICABA" },
  "350075": { nome: "Alambari",                         gve: "SOROCABA" },
  "350080": { nome: "Alfredo Marcondes",         gve: "PRESIDENTE PRUDENTE" },
  "350090": { nome: "Altair",                    gve: "BARRETOS" },
  "350115": { nome: "Aluminio",                         gve: "SOROCABA" },
  "350120": { nome: "Álvares Florence",          gve: "SAO JOSE DO RIO PRETO" },
  "350130": { nome: "Alvares Machado",                  gve: "PRESIDENTE PRUDENTE" },
  "350140": { nome: "Álvaro de Carvalho",        gve: "MARILIA" },
  "350150": { nome: "Alvinlândia",               gve: "MARILIA" },
  "350170": { nome: "Americo Brasiliense",              gve: "ARARAQUARA" },
  "350180": { nome: "Américo de Campos",         gve: "SAO JOSE DO RIO PRETO" },
  "350190": { nome: "Amparo",                           gve: "CAMPINAS" },
  "350200": { nome: "Analândia",                 gve: "PIRACICABA" },
  "350240": { nome: "Anhumas",                          gve: "PRESIDENTE PRUDENTE" },
  "350250": { nome: "Aparecida",                 gve: "TAUBATE" },
  "350260": { nome: "Aparecida d'Oeste",         gve: "JALES" },
  "350275": { nome: "Aracariguama",                     gve: "SOROCABA" },
  "350280": { nome: "Araçatuba",                 gve: "ARACATUBA" },
  "350300": { nome: "Aramina",                          gve: "FRANCA" },
  "350310": { nome: "Arandu",                    gve: "BOTUCATU" },
  "350315": { nome: "Arapei",                           gve: "TAUBATE" },
  "350320": { nome: "Araraquara",                gve: "ARARAQUARA" },
  "350330": { nome: "Araras",                    gve: "PIRACICABA" },
  "350335": { nome: "Arco-Íris",                 gve: "MARILIA" },
  "350360": { nome: "Areiopolis",                       gve: "BOTUCATU" },
  "350370": { nome: "Ariranha",                  gve: "SAO JOSE DO RIO PRETO" },
  "350380": { nome: "Artur Nogueira",                   gve: "CAMPINAS" },
  "350390": { nome: "Arujá",                     gve: "MOGI DAS CRUZES" },
  "350395": { nome: "Aspásia",                   gve: "JALES" },
  "350400": { nome: "Assis",                     gve: "ASSIS" },
  "350410": { nome: "Atibaia",                   gve: "CAMPINAS" },
  "350440": { nome: "Avanhandava",                      gve: "ARACATUBA" },
  "350450": { nome: "Avaré",                     gve: "BOTUCATU" },
  "350460": { nome: "Bady Bassitt",              gve: "SAO JOSE DO RIO PRETO" },
  "350470": { nome: "Balbinos",                         gve: "BAURU" },
  "350480": { nome: "Bálsamo",                   gve: "SAO JOSE DO RIO PRETO" },
  "350530": { nome: "Barra Bonita",                     gve: "BAURU" },
  "350535": { nome: "Barra do Chapéu",           gve: "ITAPEVA" },
  "350540": { nome: "Barra do Turvo",            gve: "REGISTRO" },
  "350550": { nome: "Barretos",                  gve: "BARRETOS" },
  "350560": { nome: "Barrinha",                         gve: "RIBEIRAO PRETO" },
  "350570": { nome: "Barueri",                   gve: "OSASCO" },
  "350580": { nome: "Bastos",                    gve: "MARILIA" },
  "350590": { nome: "Batatais",                         gve: "RIBEIRAO PRETO" },
  "350600": { nome: "Bauru",                     gve: "BAURU" },
  "350610": { nome: "Bebedouro",                 gve: "BARRETOS" },
  "350635": { nome: "Bertioga",                  gve: "SANTOS" },
  "350640": { nome: "Bilac",                            gve: "ARACATUBA" },
  "350650": { nome: "Birigui",                   gve: "ARACATUBA" },
  "350660": { nome: "Biritiba Mirim",            gve: "MOGI DAS CRUZES" },
  "350620": { nome: "Bento de Abreu",                   gve: "ARACATUBA" },
  "350630": { nome: "Bernardino de Campos",      gve: "ASSIS" },
  "350715": { nome: "Bom Sucesso de Itarare",           gve: "ITAPEVA" },
  "350720": { nome: "Borá",                      gve: "ASSIS" },
  "350740": { nome: "Borborema",                        gve: "ARARAQUARA" },
  "350745": { nome: "Borebi",                    gve: "BAURU" },
  "350750": { nome: "Botucatu",                  gve: "BOTUCATU" },
  "350760": { nome: "Braganca Paulista",                gve: "CAMPINAS" },
  "350770": { nome: "Braúna",                    gve: "ARACATUBA" },
  "350820": { nome: "Buritizal",                        gve: "FRANCA" },
  "350830": { nome: "Cabrália Paulista",         gve: "BAURU" },
  "350840": { nome: "Cabreuva",                         gve: "CAMPINAS" },
  "350850": { nome: "Caçapava",                  gve: "SAO JOSE DOS CAMPOS" },
  "350860": { nome: "Cachoeira Paulista",               gve: "TAUBATE" },
  "350870": { nome: "Caconde",                   gve: "SAO JOAO DA BOA VISTA" },
  "350900": { nome: "Caieiras",                         gve: "FRANCO DA ROCHA" },
  "350910": { nome: "Caiuá",                     gve: "PRESIDENTE VENCESLAU" },
  "350920": { nome: "Cajamar",                   gve: "FRANCO DA ROCHA" },
  "350925": { nome: "Cajati",                    gve: "REGISTRO" },
  "350930": { nome: "Cajobi",                    gve: "BARRETOS" },
  "350940": { nome: "Cajuru",                    gve: "RIBEIRAO PRETO" },
  "350945": { nome: "Campina do Monte Alegre",          gve: "SOROCABA" },
  "350950": { nome: "Campinas",                  gve: "CAMPINAS" },
  "350960": { nome: "Campo Limpo Paulista",             gve: "CAMPINAS" },
  "350970": { nome: "Campos do Jordão",          gve: "TAUBATE" },
  "350980": { nome: "Campos Novos Paulista",     gve: "MARILIA" },
  "350995": { nome: "Canas",                            gve: "TAUBATE" },
  "351000": { nome: "Cândido Mota",              gve: "ASSIS" },
  "351010": { nome: "Cândido Rodrigues",         gve: "ARARAQUARA" },
  "351015": { nome: "Canitar",                   gve: "ASSIS" },
  "351030": { nome: "Capela do Alto",                   gve: "SOROCABA" },
  "351040": { nome: "Capivari",                  gve: "PIRACICABA" },
  "351050": { nome: "Caraguatatuba",             gve: "CARAGUATATUBA" },
  "351060": { nome: "Carapicuíba",               gve: "OSASCO" },
  "351070": { nome: "Cardoso",                   gve: "SAO JOSE DO RIO PRETO" },
  "351080": { nome: "Casa Branca",               gve: "SAO JOAO DA BOA VISTA" },
  "351090": { nome: "Cassia dos Coqueiros",             gve: "RIBEIRAO PRETO" },
  "351100": { nome: "Castilho",                  gve: "ARACATUBA" },
  "351110": { nome: "Catanduva",                 gve: "SAO JOSE DO RIO PRETO" },
  "351160": { nome: "Cesario Lange",                    gve: "SOROCABA" },
  "351170": { nome: "Charqueada",                gve: "PIRACICABA" },
  "351190": { nome: "Clementina",                gve: "ARACATUBA" },
  "351200": { nome: "Colina",                    gve: "BARRETOS" },
  "351210": { nome: "Colômbia",                  gve: "BARRETOS" },
  "351220": { nome: "Conchal",                   gve: "PIRACICABA" },
  "351230": { nome: "Conchas",                          gve: "BOTUCATU" },
  "351240": { nome: "Cordeirópolis",             gve: "PIRACICABA" },
  "351260": { nome: "Coronel Macedo",                   gve: "BOTUCATU" },
  "351270": { nome: "Corumbataí",                gve: "PIRACICABA" },
  "351280": { nome: "Cosmopolis",                       gve: "CAMPINAS" },
  "351290": { nome: "Cosmorama",                 gve: "SAO JOSE DO RIO PRETO" },
  "351300": { nome: "Cotia",                     gve: "OSASCO" },
  "351310": { nome: "Cravinhos",                 gve: "RIBEIRAO PRETO" },
  "351320": { nome: "Cristais Paulista",                gve: "FRANCA" },
  "351330": { nome: "Cruzália",                  gve: "ASSIS" },
  "351340": { nome: "Cruzeiro",                         gve: "TAUBATE" },
  "351350": { nome: "Cubatão",                   gve: "SANTOS" },
  "351360": { nome: "Cunha",                            gve: "TAUBATE" },
  "351370": { nome: "Descalvado",                gve: "ARARAQUARA" },
  "351380": { nome: "Diadema",                   gve: "SANTO ANDRE" },
  "351385": { nome: "Dirce Reis",                gve: "JALES" },
  "351390": { nome: "Divinolândia",              gve: "SAO JOAO DA BOA VISTA" },
  "351410": { nome: "Dois Corregos",                    gve: "BAURU" },
  "351420": { nome: "Dolcinópolis",              gve: "JALES" },
  "351450": { nome: "Duartina",                         gve: "BAURU" },
  "351460": { nome: "Dumont",                    gve: "RIBEIRAO PRETO" },
  "351470": { nome: "Echaporã",                  gve: "MARILIA" },
  "351480": { nome: "Eldorado",                  gve: "REGISTRO" },
  "351490": { nome: "Elias Fausto",              gve: "PIRACICABA" },
  "351492": { nome: "ElisiArio",                        gve: "SAO JOSE DO RIO PRETO" },
  "351495": { nome: "Embaúba",                   gve: "SAO JOSE DO RIO PRETO" },
  "351500": { nome: "Embu das Artes",            gve: "OSASCO" },
  "351510": { nome: "Embu-Guaçu",               gve: "OSASCO" },
  "351512": { nome: "Emilianopolis",                    gve: "PRESIDENTE PRUDENTE" },
  "351515": { nome: "Engenheiro Coelho",         gve: "PIRACICABA" },
  "351518": { nome: "Espírito Santo do Pinhal",  gve: "SAO JOAO DA BOA VISTA" },
  "351519": { nome: "Espírito Santo do Turvo",   gve: "ASSIS" },
  "351520": { nome: "Estrela d'Oeste",           gve: "JALES" },
  "351530": { nome: "Estrela do Norte",                 gve: "PRESIDENTE PRUDENTE" },
  "351535": { nome: "Euclides da Cunha Paulista", gve: "PRESIDENTE VENCESLAU" },
  "351540": { nome: "Fartura",                   gve: "BOTUCATU" },
  "351550": { nome: "Fernandópolis",             gve: "JALES" },
  "351560": { nome: "Fernando Prestes",          gve: "SAO JOSE DO RIO PRETO" },
  "351565": { nome: "Fernão",                    gve: "MARILIA" },
  "351570": { nome: "Ferraz de Vasconcelos",     gve: "MOGI DAS CRUZES" },
  "351580": { nome: "Flora Rica",                gve: "PRESIDENTE VENCESLAU" },
  "351590": { nome: "Floreal",                   gve: "SAO JOSE DO RIO PRETO" },
  "351600": { nome: "Flórida Paulista",          gve: "MARILIA" },
  "351610": { nome: "Florínia",                  gve: "ASSIS" },
  "351620": { nome: "Franca",                           gve: "FRANCA" },
  "351630": { nome: "Francisco Morato",          gve: "FRANCO DA ROCHA" },
  "351640": { nome: "Franco da Rocha",           gve: "FRANCO DA ROCHA" },
  "351650": { nome: "Gabriel Monteiro",          gve: "ARACATUBA" },
  "351660": { nome: "Gália",                     gve: "MARILIA" },
  "351670": { nome: "Garça",                     gve: "MARILIA" },
  "351680": { nome: "Gastão Vidigal",            gve: "SAO JOSE DO RIO PRETO" },
  "351685": { nome: "Gavião Peixoto",            gve: "ARARAQUARA" },
  "351690": { nome: "General Salgado",           gve: "SAO JOSE DO RIO PRETO" },
  "351720": { nome: "Guaicara",                         gve: "BAURU" },
  "351730": { nome: "Guaimbê",                   gve: "MARILIA" },
  "351740": { nome: "Guaíra",                    gve: "BARRETOS" },
  "351750": { nome: "Guapiaçu",                  gve: "SAO JOSE DO RIO PRETO" },
  "351760": { nome: "Guapiara",                         gve: "ITAPEVA" },
  "351770": { nome: "Guará",                     gve: "FRANCA" },
  "351780": { nome: "Guaraçaí",                  gve: "ARACATUBA" },
  "351790": { nome: "Guaraci",                   gve: "BARRETOS" },
  "351800": { nome: "Guarani d'Oeste",           gve: "JALES" },
  "351810": { nome: "Guarantã",                  gve: "MARILIA" },
  "351820": { nome: "Guararapes",                       gve: "ARACATUBA" },
  "351830": { nome: "Guararema",                 gve: "MOGI DAS CRUZES" },
  "351840": { nome: "Guaratinguetá",             gve: "TAUBATE" },
  "351860": { nome: "Guariba",                          gve: "RIBEIRAO PRETO" },
  "351870": { nome: "Guarujá",                   gve: "SANTOS" },
  "351880": { nome: "Guarulhos",                 gve: "MOGI DAS CRUZES" },
  "351890": { nome: "Guzolandia",                       gve: "ARACATUBA" },
  "351900": { nome: "Herculândia",               gve: "MARILIA" },
  "351910": { nome: "Iacanga",                          gve: "BAURU" },
  "351920": { nome: "Iacri",                     gve: "MARILIA" },
  "351925": { nome: "Iaras",                            gve: "BOTUCATU" },
  "351930": { nome: "Ibaté",                     gve: "ARARAQUARA" },
  "351940": { nome: "Ibirá",                     gve: "SAO JOSE DO RIO PRETO" },
  "351950": { nome: "Ibirarema",                 gve: "ASSIS" },
  "351970": { nome: "Ibiuna",                           gve: "SOROCABA" },
  "351980": { nome: "Icém",                      gve: "SAO JOSE DO RIO PRETO" },
  "352020": { nome: "Igarata",                          gve: "SAO JOSE DOS CAMPOS" },
  "352030": { nome: "Iguape",                    gve: "REGISTRO" },
  "352040": { nome: "Ilhabela",                         gve: "CARAGUATATUBA" },
  "352042": { nome: "Ilha Comprida",             gve: "REGISTRO" },
  "352060": { nome: "Indiana",                          gve: "PRESIDENTE PRUDENTE" },
  "352070": { nome: "Indiaporã",                 gve: "JALES" },
  "352080": { nome: "Inúbia Paulista",           gve: "MARILIA" },
  "352090": { nome: "Ipaussu",                   gve: "ASSIS" },
  "352100": { nome: "Ipero",                            gve: "SOROCABA" },
  "352110": { nome: "Ipeúna",                    gve: "PIRACICABA" },
  "352115": { nome: "Ipiguá",                    gve: "SAO JOSE DO RIO PRETO" },
  "352120": { nome: "Iporanga",                  gve: "REGISTRO" },
  "352130": { nome: "Ipuã",                      gve: "FRANCA" },
  "352140": { nome: "Iracemápolis",              gve: "PIRACICABA" },
  "352150": { nome: "Irapuã",                    gve: "SAO JOSE DO RIO PRETO" },
  "352160": { nome: "Irapuru",                          gve: "PRESIDENTE VENCESLAU" },
  "352170": { nome: "Itaberá",                   gve: "ITAPEVA" },
  "352180": { nome: "Itai",                             gve: "BOTUCATU" },
  "352190": { nome: "Itajobi",                   gve: "SAO JOSE DO RIO PRETO" },
  "352200": { nome: "Itaju",                            gve: "BAURU" },
  "352210": { nome: "Itanhaém",                  gve: "SANTOS" },
  "352215": { nome: "Itaoca",                    gve: "ITAPEVA" },
  "352220": { nome: "Itapecerica da Serra",      gve: "OSASCO" },
  "352230": { nome: "Itapetininga",                     gve: "SOROCABA" },
  "352240": { nome: "Itapeva",                   gve: "ITAPEVA" },
  "352250": { nome: "Itapevi",                   gve: "OSASCO" },
  "352260": { nome: "Itapira",                   gve: "SAO JOAO DA BOA VISTA" },
  "352265": { nome: "Itapirapuã Paulista",       gve: "ITAPEVA" },
  "352270": { nome: "Itapolis",                         gve: "ARARAQUARA" },
  "352280": { nome: "Itaporanga",                gve: "BOTUCATU" },
  "352300": { nome: "Itapura",                          gve: "ARACATUBA" },
  "352310": { nome: "Itaquaquecetuba",           gve: "MOGI DAS CRUZES" },
  "352320": { nome: "Itararé",                   gve: "ITAPEVA" },
  "352330": { nome: "Itariri",                   gve: "REGISTRO" },
  "352340": { nome: "Itatiba",                   gve: "CAMPINAS" },
  "352350": { nome: "Itatinga",                         gve: "BOTUCATU" },
  "352360": { nome: "Itirapina",                 gve: "PIRACICABA" },
  "352370": { nome: "Itirapua",                         gve: "FRANCA" },
  "352380": { nome: "Itobi",                     gve: "SAO JOAO DA BOA VISTA" },
  "352390": { nome: "Itu",                       gve: "SOROCABA" },
  "352410": { nome: "Ituverava",                        gve: "FRANCA" },
  "352420": { nome: "Jaborandi",                 gve: "BARRETOS" },
  "352430": { nome: "Jaboticabal",                      gve: "RIBEIRAO PRETO" },
  "352440": { nome: "Jacareí",                   gve: "SAO JOSE DOS CAMPOS" },
  "352450": { nome: "Jaci",                             gve: "SAO JOSE DO RIO PRETO" },
  "352460": { nome: "Jacupiranga",               gve: "REGISTRO" },
  "352470": { nome: "Jaguariuna",                       gve: "CAMPINAS" },
  "352480": { nome: "Jales",                     gve: "JALES" },
  "352490": { nome: "Jambeiro",                         gve: "SAO JOSE DOS CAMPOS" },
  "352500": { nome: "Jandira",                   gve: "OSASCO" },
  "352520": { nome: "Jarinu",                           gve: "CAMPINAS" },
  "352530": { nome: "Jaú",                       gve: "BAURU" },
  "352560": { nome: "Joao Ramalho",                     gve: "PRESIDENTE PRUDENTE" },
  "352570": { nome: "José Bonifácio",            gve: "SAO JOSE DO RIO PRETO" },
  "352580": { nome: "Júlio Mesquita",            gve: "MARILIA" },
  "352585": { nome: "Jumirim",                   gve: "SOROCABA" },
  "352590": { nome: "Jundiaí",                   gve: "CAMPINAS" },
  "352600": { nome: "Junqueiropolis",                   gve: "PRESIDENTE VENCESLAU" },
  "352610": { nome: "Juquiá",                    gve: "REGISTRO" },
  "352620": { nome: "Juquitiba",                 gve: "OSASCO" },
  "352630": { nome: "Lagoinha",                  gve: "TAUBATE" },
  "352650": { nome: "Lavinia",                          gve: "ARACATUBA" },
  "352660": { nome: "Lavrinhas",                 gve: "TAUBATE" },
  "352670": { nome: "Leme",                      gve: "PIRACICABA" },
  "352680": { nome: "Lencois Paulista",                 gve: "BAURU" },
  "352690": { nome: "Limeira",                   gve: "PIRACICABA" },
  "352700": { nome: "Lindoia",                          gve: "CAMPINAS" },
  "352710": { nome: "Lins",                      gve: "BAURU" },
  "352720": { nome: "Lorena",                    gve: "TAUBATE" },
  "352730": { nome: "Louveira",                         gve: "CAMPINAS" },
  "352740": { nome: "Lucélia",                   gve: "MARILIA" },
  "352750": { nome: "Lucianópolis",              gve: "BAURU" },
  "352760": { nome: "Luís Antônio",              gve: "RIBEIRAO PRETO" },
  "352770": { nome: "Luiziania",                        gve: "ARACATUBA" },
  "352780": { nome: "Lupércio",                  gve: "MARILIA" },
  "352790": { nome: "Lutécia",                   gve: "ASSIS" },
  "352800": { nome: "Macatuba",                  gve: "BAURU" },
  "352810": { nome: "Macaubal",                  gve: "SAO JOSE DO RIO PRETO" },
  "352820": { nome: "Macedônia",                 gve: "JALES" },
  "352830": { nome: "Magda",                     gve: "SAO JOSE DO RIO PRETO" },
  "352840": { nome: "Mairinque",                        gve: "SOROCABA" },
  "352850": { nome: "Mairiporã",                 gve: "FRANCO DA ROCHA" },
  "352860": { nome: "Manduri",                          gve: "BOTUCATU" },
  "352870": { nome: "Marabá Paulista",           gve: "PRESIDENTE VENCESLAU" },
  "352880": { nome: "Maracaí",                   gve: "ASSIS" },
  "352885": { nome: "Marapoama",                 gve: "SAO JOSE DO RIO PRETO" },
  "352890": { nome: "Mariápolis",                gve: "MARILIA" },
  "352900": { nome: "Marília",                   gve: "MARILIA" },
  "352910": { nome: "Marinópolis",               gve: "JALES" },
  "352920": { nome: "Martinópolis",              gve: "PRESIDENTE PRUDENTE" },
  "352930": { nome: "Matão",                     gve: "ARARAQUARA" },
  "352940": { nome: "Mauá",                      gve: "SANTO ANDRE" },
  "352950": { nome: "Mendonça",                  gve: "SAO JOSE DO RIO PRETO" },
  "352960": { nome: "Meridiano",                 gve: "JALES" },
  "352965": { nome: "Mesópolis",                 gve: "JALES" },
  "352980": { nome: "Mineiros do Tiete",                gve: "BAURU" },
  "352990": { nome: "Miracatu",                  gve: "REGISTRO" },
  "353000": { nome: "Mira Estrela",              gve: "JALES" },
  "353010": { nome: "Mirandópolis",              gve: "ARACATUBA" },
  "353020": { nome: "Mirante do Paranapanema",          gve: "PRESIDENTE VENCESLAU" },
  "353030": { nome: "Mirassol",                  gve: "SAO JOSE DO RIO PRETO" },
  "353040": { nome: "Mirassolandia",                    gve: "SAO JOSE DO RIO PRETO" },
  "353050": { nome: "Mococa",                    gve: "SAO JOAO DA BOA VISTA" },
  "353060": { nome: "Mogi das Cruzes",           gve: "MOGI DAS CRUZES" },
  "353070": { nome: "Mogi Guaçu",               gve: "SAO JOAO DA BOA VISTA" },
  "353080": { nome: "Mogi Mirim",                gve: "SAO JOAO DA BOA VISTA" },
  "353090": { nome: "Mombuca",                   gve: "PIRACICABA" },
  "353100": { nome: "Monções",                   gve: "SAO JOSE DO RIO PRETO" },
  "353110": { nome: "Mongaguá",                  gve: "SANTOS" },
  "353120": { nome: "Monte Alegre do Sul",              gve: "CAMPINAS" },
  "353130": { nome: "Monte Alto",                gve: "RIBEIRAO PRETO" },
  "353140": { nome: "Monte Aprazível",           gve: "SAO JOSE DO RIO PRETO" },
  "353150": { nome: "Monte Azul Paulista",       gve: "BARRETOS" },
  "353160": { nome: "Monte Castelo",             gve: "PRESIDENTE VENCESLAU" },
  "353170": { nome: "Monteiro Lobato",           gve: "SAO JOSE DOS CAMPOS" },
  "353200": { nome: "Morungaba",                        gve: "CAMPINAS" },
  "353205": { nome: "Motuca",                    gve: "ARARAQUARA" },
  "353215": { nome: "Nantes",                           gve: "PRESIDENTE PRUDENTE" },
  "353220": { nome: "Narandiba",                 gve: "PRESIDENTE PRUDENTE" },
  "353230": { nome: "Natividade da Serra",       gve: "TAUBATE" },
  "353240": { nome: "Nazare Paulista",                  gve: "CAMPINAS" },
  "353250": { nome: "Neves Paulista",            gve: "SAO JOSE DO RIO PRETO" },
  "353260": { nome: "Nhandeara",                 gve: "SAO JOSE DO RIO PRETO" },
  "353280": { nome: "Nova Alianca",                     gve: "SAO JOSE DO RIO PRETO" },
  "353282": { nome: "Nova Campina",              gve: "ITAPEVA" },
  "353284": { nome: "Nova Canaã Paulista",       gve: "JALES" },
  "353286": { nome: "Nova Castilho",             gve: "ARACATUBA" },
  "353290": { nome: "Nova Europa",               gve: "ARARAQUARA" },
  "353300": { nome: "Nova Granada",              gve: "SAO JOSE DO RIO PRETO" },
  "353340": { nome: "Nova Odessa",                      gve: "CAMPINAS" },
  "353350": { nome: "Novo Horizonte",            gve: "SAO JOSE DO RIO PRETO" },
  "353360": { nome: "Nuporanga",                        gve: "FRANCA" },
  "353370": { nome: "Ocauçu",                    gve: "MARILIA" },
  "353380": { nome: "Óleo",                      gve: "ASSIS" },
  "353390": { nome: "Olímpia",                   gve: "BARRETOS" },
  "353400": { nome: "Onda Verde",                gve: "SAO JOSE DO RIO PRETO" },
  "353410": { nome: "Oriente",                   gve: "MARILIA" },
  "353420": { nome: "Orindiúva",                 gve: "SAO JOSE DO RIO PRETO" },
  "353430": { nome: "Orlandia",                         gve: "FRANCA" },
  "353440": { nome: "Osasco",                    gve: "OSASCO" },
  "353450": { nome: "Oscar Bressane",            gve: "MARILIA" },
  "353460": { nome: "Osvaldo Cruz",              gve: "MARILIA" },
  "353470": { nome: "Ourinhos",                  gve: "ASSIS" },
  "353475": { nome: "Ouroeste",                  gve: "JALES" },
  "353480": { nome: "Ouro Verde",                       gve: "PRESIDENTE VENCESLAU" },
  "353490": { nome: "Pacaembu",                  gve: "MARILIA" },
  "353500": { nome: "Palestina",                 gve: "SAO JOSE DO RIO PRETO" },
  "353510": { nome: "Palmares Paulista",         gve: "SAO JOSE DO RIO PRETO" },
  "353520": { nome: "Palmeira d'Oeste",          gve: "JALES" },
  "353530": { nome: "Palmital",                  gve: "ASSIS" },
  "353540": { nome: "Panorama",                         gve: "PRESIDENTE VENCESLAU" },
  "353550": { nome: "Paraguaçu Paulista",        gve: "ASSIS" },
  "353560": { nome: "Paraibuna",                 gve: "SAO JOSE DOS CAMPOS" },
  "353570": { nome: "Paraíso",                   gve: "SAO JOSE DO RIO PRETO" },
  "353580": { nome: "Paranapanema",                     gve: "BOTUCATU" },
  "353590": { nome: "Paranapuã",                 gve: "JALES" },
  "353600": { nome: "Parapuã",                   gve: "MARILIA" },
  "353610": { nome: "Pardinho",                         gve: "BOTUCATU" },
  "353620": { nome: "Pariquera-Açu",             gve: "REGISTRO" },
  "353625": { nome: "Parisi",                    gve: "SAO JOSE DO RIO PRETO" },
  "353640": { nome: "Pauliceia",                        gve: "PRESIDENTE VENCESLAU" },
  "353650": { nome: "Paulínia",                  gve: "CAMPINAS" },
  "353657": { nome: "Paulistânia",               gve: "BAURU" },
  "353660": { nome: "Paulo de Faria",            gve: "SAO JOSE DO RIO PRETO" },
  "353680": { nome: "Pedra Bela",                       gve: "CAMPINAS" },
  "353690": { nome: "Pedranópolis",              gve: "JALES" },
  "353710": { nome: "Pedreira",                         gve: "CAMPINAS" },
  "353715": { nome: "Pedrinhas Paulista",        gve: "ASSIS" },
  "353720": { nome: "Pedro de Toledo",           gve: "REGISTRO" },
  "353730": { nome: "Penapolis",                        gve: "ARACATUBA" },
  "353740": { nome: "Pereira Barreto",           gve: "ARACATUBA" },
  "353750": { nome: "Pereiras",                         gve: "BOTUCATU" },
  "353760": { nome: "Peruíbe",                   gve: "SANTOS" },
  "353770": { nome: "Piacatu",                          gve: "ARACATUBA" },
  "353780": { nome: "Piedade",                   gve: "SOROCABA" },
  "353800": { nome: "Pindamonhangaba",                  gve: "TAUBATE" },
  "353810": { nome: "Pindorama",                 gve: "SAO JOSE DO RIO PRETO" },
  "353820": { nome: "Pinhalzinho",                      gve: "CAMPINAS" },
  "353830": { nome: "Piquerobi",                 gve: "PRESIDENTE VENCESLAU" },
  "353850": { nome: "Piquete",                   gve: "TAUBATE" },
  "353860": { nome: "Piracaia",                         gve: "CAMPINAS" },
  "353870": { nome: "Piracicaba",                gve: "PIRACICABA" },
  "353880": { nome: "Piraju",                           gve: "BOTUCATU" },
  "353890": { nome: "Pirajuí",                   gve: "BAURU" },
  "353900": { nome: "Pirangi",                   gve: "SAO JOSE DO RIO PRETO" },
  "353910": { nome: "Pirapora do Bom Jesus",     gve: "OSASCO" },
  "353920": { nome: "Pirapozinho",               gve: "PRESIDENTE PRUDENTE" },
  "353940": { nome: "Piratininga",                      gve: "BAURU" },
  "353950": { nome: "Pitangueiras",              gve: "RIBEIRAO PRETO" },
  "353960": { nome: "Planalto",                  gve: "SAO JOSE DO RIO PRETO" },
  "353970": { nome: "Platina",                   gve: "ASSIS" },
  "353980": { nome: "Poá",                       gve: "MOGI DAS CRUZES" },
  "353990": { nome: "Poloni",                    gve: "SAO JOSE DO RIO PRETO" },
  "354000": { nome: "Pompéia",                   gve: "MARILIA" },
  "354020": { nome: "Pontal",                           gve: "RIBEIRAO PRETO" },
  "354025": { nome: "Pontalinda",                gve: "JALES" },
  "354030": { nome: "Pontes Gestal",             gve: "SAO JOSE DO RIO PRETO" },
  "354040": { nome: "Populina",                  gve: "JALES" },
  "354050": { nome: "Porangaba",                 gve: "BOTUCATU" },
  "354075": { nome: "Potim",                            gve: "TAUBATE" },
  "354080": { nome: "Potirendaba",               gve: "SAO JOSE DO RIO PRETO" },
  "354085": { nome: "Pracinha",                  gve: "MARILIA" },
  "354090": { nome: "Pradópolis",                gve: "RIBEIRAO PRETO" },
  "354100": { nome: "Praia Grande",              gve: "SANTOS" },
  "354130": { nome: "Presidente EpitAcio",              gve: "PRESIDENTE VENCESLAU" },
  "354140": { nome: "Presidente Prudente",       gve: "PRESIDENTE PRUDENTE" },
  "354150": { nome: "Presidente Venceslau",             gve: "PRESIDENTE VENCESLAU" },
  "354165": { nome: "Quadra",                    gve: "SOROCABA" },
  "354170": { nome: "Quata",                            gve: "PRESIDENTE PRUDENTE" },
  "354180": { nome: "Queiroz",                   gve: "MARILIA" },
  "354190": { nome: "Queluz",                           gve: "TAUBATE" },
  "354200": { nome: "Quintana",                  gve: "MARILIA" },
  "354210": { nome: "Rafard",                    gve: "PIRACICABA" },
  "354230": { nome: "Redencao da Serra",                gve: "TAUBATE" },
  "354240": { nome: "Regente Feijó",             gve: "PRESIDENTE PRUDENTE" },
  "354260": { nome: "Registro",                  gve: "REGISTRO" },
  "354270": { nome: "Restinga",                         gve: "FRANCA" },
  "354280": { nome: "Ribeira",                   gve: "ITAPEVA" },
  "354290": { nome: "Ribeirao Bonito",                  gve: "ARARAQUARA" },
  "354300": { nome: "Ribeirão Branco",           gve: "ITAPEVA" },
  "354320": { nome: "Ribeirão do Sul",           gve: "ASSIS" },
  "354310": { nome: "Ribeirão Corrente",         gve: "FRANCA" },
  "354323": { nome: "Ribeirão dos Índios",       gve: "PRESIDENTE PRUDENTE" },
  "354325": { nome: "Ribeirao Grande",                  gve: "SOROCABA" },
  "354330": { nome: "Ribeirão Pires",            gve: "SANTO ANDRE" },
  "354340": { nome: "Ribeirão Preto",            gve: "RIBEIRAO PRETO" },
  "354350": { nome: "Riversul",                  gve: "ITAPEVA" },
  "354360": { nome: "Rifaina",                          gve: "FRANCA" },
  "354370": { nome: "Rincão",                    gve: "ARARAQUARA" },
  "354380": { nome: "Rinópolis",                 gve: "MARILIA" },
  "354390": { nome: "Rio Claro",                 gve: "PIRACICABA" },
  "354400": { nome: "Rio das Pedras",            gve: "PIRACICABA" },
  "354410": { nome: "Rio Grande da Serra",       gve: "SANTO ANDRE" },
  "354420": { nome: "Riolândia",                 gve: "SAO JOSE DO RIO PRETO" },
  "354425": { nome: "Rosana",                    gve: "PRESIDENTE VENCESLAU" },
  "354440": { nome: "Rubiacea",                         gve: "ARACATUBA" },
  "354450": { nome: "Rubinéia",                  gve: "JALES" },
  "354470": { nome: "Sagres",                    gve: "MARILIA" },
  "354480": { nome: "Sales",                     gve: "SAO JOSE DO RIO PRETO" },
  "354490": { nome: "Sales Oliveira",                   gve: "FRANCA" },
  "354500": { nome: "Salesópolis",               gve: "MOGI DAS CRUZES" },
  "354510": { nome: "Salmourão",                 gve: "MARILIA" },
  "354515": { nome: "Saltinho",                  gve: "PIRACICABA" },
  "354520": { nome: "Salto",                            gve: "SOROCABA" },
  "354530": { nome: "Salto de Pirapora",         gve: "SOROCABA" },
  "354540": { nome: "Salto Grande",              gve: "ASSIS" },
  "354550": { nome: "Sandovalina",                      gve: "PRESIDENTE PRUDENTE" },
  "354560": { nome: "Santa Adélia",              gve: "SAO JOSE DO RIO PRETO" },
  "354570": { nome: "Santa Albertina",           gve: "JALES" },
  "354600": { nome: "Santa Branca",                     gve: "SAO JOSE DOS CAMPOS" },
  "354610": { nome: "Santa Clara d'Oeste",       gve: "JALES" },
  "354620": { nome: "Santa Cruz da Conceição",   gve: "PIRACICABA" },
  "354625": { nome: "Santa Cruz da Esperança",   gve: "RIBEIRAO PRETO" },
  "354630": { nome: "Santa Cruz das Palmeiras",  gve: "SAO JOAO DA BOA VISTA" },
  "354640": { nome: "Santa Cruz do Rio Pardo",   gve: "ASSIS" },
  "354650": { nome: "Santa Ernestina",                  gve: "ARARAQUARA" },
  "354660": { nome: "Santa Fé do Sul",           gve: "JALES" },
  "354670": { nome: "Santa Gertrudes",           gve: "PIRACICABA" },
  "354690": { nome: "Santa Lucia",                      gve: "ARARAQUARA" },
  "354700": { nome: "Santa Maria da Serra",      gve: "PIRACICABA" },
  "354710": { nome: "Santa Mercedes",            gve: "PRESIDENTE VENCESLAU" },
  "354720": { nome: "Santana da Ponte Pensa",    gve: "JALES" },
  "354730": { nome: "Santana de Parnaíba",       gve: "OSASCO" },
  "354740": { nome: "Santa Rita d'Oeste",        gve: "JALES" },
  "354760": { nome: "Santa Rosa de Viterbo",            gve: "RIBEIRAO PRETO" },
  "354765": { nome: "Santa Salete",              gve: "JALES" },
  "354770": { nome: "Santo Anastácio",           gve: "PRESIDENTE PRUDENTE" },
  "354780": { nome: "Santo André",               gve: "SANTO ANDRE" },
  "354790": { nome: "Santo Antônio da Alegria",  gve: "RIBEIRAO PRETO" },
  "354805": { nome: "Santo Antonio do Aracangua",       gve: "ARACATUBA" },
  "354810": { nome: "Santo Antônio do Jardim",   gve: "SAO JOAO DA BOA VISTA" },
  "354820": { nome: "Santo Antonio do Pinhal",          gve: "TAUBATE" },
  "354830": { nome: "Santo Expedito",            gve: "PRESIDENTE PRUDENTE" },
  "354840": { nome: "Santópolis do Aguapeí",     gve: "ARACATUBA" },
  "354850": { nome: "Santos",                    gve: "SANTOS" },
  "354880": { nome: "São Caetano do Sul",        gve: "SANTO ANDRE" },
  "354890": { nome: "São Carlos",                gve: "ARARAQUARA" },
  "354900": { nome: "São Francisco",             gve: "JALES" },
  "354910": { nome: "São João da Boa Vista",     gve: "SAO JOAO DA BOA VISTA" },
  "354920": { nome: "São João das Duas Pontes",  gve: "JALES" },
  "354925": { nome: "São João de Iracema",       gve: "JALES" },
  "354930": { nome: "São João do Pau d'Alho",    gve: "PRESIDENTE VENCESLAU" },
  "354950": { nome: "São José da Bela Vista",    gve: "FRANCA" },
  "354970": { nome: "São José do Rio Pardo",     gve: "SAO JOAO DA BOA VISTA" },
  "354980": { nome: "São José do Rio Preto",     gve: "SAO JOSE DO RIO PRETO" },
  "354990": { nome: "São José dos Campos",       gve: "SAO JOSE DOS CAMPOS" },
  "354995": { nome: "São Lourenço da Serra",     gve: "OSASCO" },
  "355030": { nome: "São Paulo",                 gve: "SAO PAULO" },
  "355040": { nome: "São Pedro",                 gve: "PIRACICABA" },
  "355050": { nome: "São Pedro do Turvo",        gve: "ASSIS" },
  "355070": { nome: "São Sebastião",             gve: "CARAGUATATUBA" },
  "355080": { nome: "São Sebastião da Grama",    gve: "SAO JOAO DA BOA VISTA" },
  "355100": { nome: "São Vicente",               gve: "SANTOS" },
  "355120": { nome: "Sarutaiá",                  gve: "BOTUCATU" },
  "355130": { nome: "Sebastianópolis do Sul",    gve: "SAO JOSE DO RIO PRETO" },
  "355140": { nome: "Serra Azul",                gve: "RIBEIRAO PRETO" },
  "355150": { nome: "Serrana",                   gve: "RIBEIRAO PRETO" },
  "355180": { nome: "Sete Barras",                      gve: "REGISTRO" },
  "355190": { nome: "Severínia",                 gve: "BARRETOS" },
  "355200": { nome: "Silveiras",                 gve: "TAUBATE" },
  "355210": { nome: "Socorro",                          gve: "CAMPINAS" },
  "355220": { nome: "Sorocaba",                  gve: "SOROCABA" },
  "355230": { nome: "Sud Mennucci",              gve: "ARACATUBA" },
  "355240": { nome: "Sumare",                           gve: "CAMPINAS" },
  "355250": { nome: "Suzano",                    gve: "MOGI DAS CRUZES" },
  "355255": { nome: "Suzanapolis",                      gve: "ARACATUBA" },
  "355260": { nome: "Tabapuã",                   gve: "SAO JOSE DO RIO PRETO" },
  "355270": { nome: "Tabatinga",                        gve: "ARARAQUARA" },
  "355280": { nome: "Taboão da Serra",           gve: "OSASCO" },
  "355290": { nome: "Taciba",                           gve: "PRESIDENTE PRUDENTE" },
  "355300": { nome: "Taguaí",                    gve: "BOTUCATU" },
  "355310": { nome: "Taiaçu",                    gve: "BARRETOS" },
  "355320": { nome: "Taiúva",                    gve: "BARRETOS" },
  "355330": { nome: "Tambaú",                    gve: "SAO JOAO DA BOA VISTA" },
  "355340": { nome: "Tanabi",                    gve: "SAO JOSE DO RIO PRETO" },
  "355360": { nome: "Tapiratiba",                gve: "SAO JOAO DA BOA VISTA" },
  "355365": { nome: "Taquaral",                  gve: "BARRETOS" },
  "355370": { nome: "Taquaritinga",              gve: "ARARAQUARA" },
  "355380": { nome: "Taquarituba",               gve: "BOTUCATU" },
  "355385": { nome: "Taquarivaí",                gve: "ITAPEVA" },
  "355390": { nome: "Tarabai",                          gve: "PRESIDENTE PRUDENTE" },
  "355395": { nome: "Tarumã",                    gve: "ASSIS" },
  "355410": { nome: "Taubaté",                   gve: "TAUBATE" },
  "355430": { nome: "Teodoro Sampaio",           gve: "PRESIDENTE VENCESLAU" },
  "355440": { nome: "Terra Roxa",                gve: "BARRETOS" },
  "355460": { nome: "Timburi",                   gve: "ASSIS" },
  "355465": { nome: "Torre de Pedra",            gve: "BOTUCATU" },
  "355475": { nome: "Trabiju",                   gve: "ARARAQUARA" },
  "355490": { nome: "Três Fronteiras",           gve: "JALES" },
  "355495": { nome: "Tuiuti",                           gve: "CAMPINAS" },
  "355500": { nome: "Tupã",                      gve: "MARILIA" },
  "355510": { nome: "Tupi Paulista",             gve: "PRESIDENTE VENCESLAU" },
  "355520": { nome: "Turiúba",                   gve: "ARACATUBA" },
  "355530": { nome: "Turmalina",                 gve: "JALES" },
  "355535": { nome: "Ubarana",                   gve: "SAO JOSE DO RIO PRETO" },
  "355550": { nome: "Ubirajara",                 gve: "MARILIA" },
  "355560": { nome: "Uchoa",                     gve: "SAO JOSE DO RIO PRETO" },
  "355570": { nome: "União Paulista",            gve: "SAO JOSE DO RIO PRETO" },
  "355580": { nome: "Urânia",                    gve: "JALES" },
  "355590": { nome: "Uru",                       gve: "BAURU" },
  "355600": { nome: "Urupês",                    gve: "SAO JOSE DO RIO PRETO" },
  "355610": { nome: "Valentim Gentil",           gve: "SAO JOSE DO RIO PRETO" },
  "355635": { nome: "Vargem",                           gve: "CAMPINAS" },
  "355640": { nome: "Vargem Grande do Sul",      gve: "SAO JOAO DA BOA VISTA" },
  "355645": { nome: "Vargem Grande Paulista",    gve: "OSASCO" },
  "355650": { nome: "Varzea Paulista",                  gve: "CAMPINAS" },
  "355660": { nome: "Vera Cruz",                 gve: "MARILIA" },
  "355670": { nome: "Vinhedo",                          gve: "CAMPINAS" },
  "355680": { nome: "Viradouro",                 gve: "BARRETOS" },
  "355690": { nome: "Vista Alegre do Alto",      gve: "BARRETOS" },
  "355695": { nome: "Vitória Brasil",            gve: "JALES" },
  "355710": { nome: "Votuporanga",               gve: "SAO JOSE DO RIO PRETO" },
  "355720": { nome: "Chavantes",                 gve: "ASSIS" },
  "355730": { nome: "Estiva Gerbi",              gve: "SAO JOAO DA BOA VISTA" },
};

/** Retorna nome e GVE do município pelo código IBGE 6 dígitos */
export function infoMunicipio(codigo: string | null | undefined): MunicipioInfo | null {
  if (!codigo) return null;
  const cod = String(codigo).trim().replace(/\D/g, "").padStart(6, "0");
  return MUNICIPIOS_SP[cod] ?? null;
}

/** Retorna apenas o nome do município (compatibilidade retroativa) */
export function nomeMunicipio(codigo: string | null | undefined): string {
  if (!codigo) return "Não informado";
  const info = infoMunicipio(codigo);
  return info?.nome ?? String(codigo).trim();
}

/** Retorna o GVE do município pelo código IBGE */
export function gvePorCodigo(codigo: string | null | undefined): string | null {
  if (!codigo) return null;
  return infoMunicipio(codigo)?.gve ?? null;
}

/** Retorna o GVE pelo nome do município (busca case-insensitive sem acento) */
export function gvePorNomeMunicipio(nome: string | null | undefined): string | null {
  if (!nome) return null;
  const normalize = (s: string) => s.trim().toUpperCase().normalize("NFD").replace(/[̀-ͯ]/g, "");
  const needle = normalize(nome);
  const entry = Object.values(MUNICIPIOS_SP).find((info) => normalize(info.nome) === needle);
  return entry?.gve ?? null;
}

export function listarMunicipiosSp() {
  return Object.entries(MUNICIPIOS_SP)
    .map(([codigo, info]) => ({ codigo, nome: info.nome, gve: info.gve }))
    .sort((a, b) => a.nome.localeCompare(b.nome, "pt-BR"));
}

export function listarGvesSp() {
  return Array.from(new Set(Object.values(MUNICIPIOS_SP).map((info) => info.gve)))
    .sort((a, b) => a.localeCompare(b, "pt-BR"));
}

export function listarMunicipiosPorGve(gve?: string | null) {
  const selected = String(gve ?? "").trim();
  return listarMunicipiosSp().filter((municipio) => !selected || municipio.gve === selected);
}
