/**
 * Lookup IBGE 6 dígitos → { nome, gve } para municípios do Estado de São Paulo.
 * Cobre todos os 331 municípios distintos presentes no banco SINAN tracoma.
 * Códigos verificados via API pública IBGE (servicodados.ibge.gov.br).
 * GVEs conforme estrutura das 28 GVEs da Secretaria de Saúde SP.
 */

export interface MunicipioInfo {
  nome: string;
  gve: string;
}

const MUNICIPIOS_SP: Record<string, MunicipioInfo> = {
  "350010": { nome: "Adamantina",               gve: "MARILIA" },
  "350020": { nome: "Adolfo",                    gve: "SAO JOSE DO RIO PRETO" },
  "350030": { nome: "Aguaí",                     gve: "SAO JOAO DA BOA VISTA" },
  "350040": { nome: "Águas da Prata",            gve: "SAO JOAO DA BOA VISTA" },
  "350055": { nome: "Águas de Santa Bárbara",    gve: "BAURU" },
  "350060": { nome: "Águas de São Pedro",        gve: "PIRACICABA" },
  "350080": { nome: "Alfredo Marcondes",         gve: "PRESIDENTE PRUDENTE" },
  "350090": { nome: "Altair",                    gve: "SAO JOSE DO RIO PRETO" },
  "350120": { nome: "Álvares Florence",          gve: "SAO JOSE DO RIO PRETO" },
  "350140": { nome: "Álvaro de Carvalho",        gve: "MARILIA" },
  "350150": { nome: "Alvinlândia",               gve: "MARILIA" },
  "350180": { nome: "Américo de Campos",         gve: "SAO JOSE DO RIO PRETO" },
  "350200": { nome: "Analândia",                 gve: "PIRACICABA" },
  "350250": { nome: "Aparecida",                 gve: "TAUBATE" },
  "350260": { nome: "Aparecida d'Oeste",         gve: "JALES" },
  "350280": { nome: "Araçatuba",                 gve: "ARACATUBA" },
  "350310": { nome: "Arandu",                    gve: "BOTUCATU" },
  "350320": { nome: "Araraquara",                gve: "ARARAQUARA" },
  "350330": { nome: "Araras",                    gve: "PIRACICABA" },
  "350335": { nome: "Arco-Íris",                 gve: "MARILIA" },
  "350370": { nome: "Ariranha",                  gve: "SAO JOSE DO RIO PRETO" },
  "350390": { nome: "Arujá",                     gve: "MOGI DAS CRUZES" },
  "350395": { nome: "Aspásia",                   gve: "JALES" },
  "350400": { nome: "Assis",                     gve: "ASSIS" },
  "350410": { nome: "Atibaia",                   gve: "CAMPINAS" },
  "350450": { nome: "Avaré",                     gve: "BOTUCATU" },
  "350460": { nome: "Bady Bassitt",              gve: "SAO JOSE DO RIO PRETO" },
  "350480": { nome: "Bálsamo",                   gve: "SAO JOSE DO RIO PRETO" },
  "350535": { nome: "Barra do Chapéu",           gve: "ITAPEVA" },
  "350540": { nome: "Barra do Turvo",            gve: "REGISTRO" },
  "350550": { nome: "Barretos",                  gve: "BARRETOS" },
  "350570": { nome: "Barueri",                   gve: "OSASCO" },
  "350580": { nome: "Bastos",                    gve: "MARILIA" },
  "350600": { nome: "Bauru",                     gve: "BAURU" },
  "350610": { nome: "Bebedouro",                 gve: "BARRETOS" },
  "350635": { nome: "Bertioga",                  gve: "SANTOS" },
  "350650": { nome: "Birigui",                   gve: "ARACATUBA" },
  "350660": { nome: "Biritiba Mirim",            gve: "MOGI DAS CRUZES" },
  "350720": { nome: "Borá",                      gve: "MARILIA" },
  "350745": { nome: "Borebi",                    gve: "BAURU" },
  "350750": { nome: "Botucatu",                  gve: "BOTUCATU" },
  "350770": { nome: "Braúna",                    gve: "ARACATUBA" },
  "350830": { nome: "Cabrália Paulista",         gve: "BAURU" },
  "350850": { nome: "Caçapava",                  gve: "SAO JOSE DOS CAMPOS" },
  "350870": { nome: "Caconde",                   gve: "SAO JOAO DA BOA VISTA" },
  "350910": { nome: "Caiuá",                     gve: "PRESIDENTE PRUDENTE" },
  "350920": { nome: "Cajamar",                   gve: "FRANCO DA ROCHA" },
  "350925": { nome: "Cajati",                    gve: "REGISTRO" },
  "350930": { nome: "Cajobi",                    gve: "SAO JOSE DO RIO PRETO" },
  "350940": { nome: "Cajuru",                    gve: "RIBEIRAO PRETO" },
  "350950": { nome: "Campinas",                  gve: "CAMPINAS" },
  "350970": { nome: "Campos do Jordão",          gve: "TAUBATE" },
  "350980": { nome: "Campos Novos Paulista",     gve: "MARILIA" },
  "351000": { nome: "Cândido Mota",              gve: "ASSIS" },
  "351010": { nome: "Cândido Rodrigues",         gve: "RIBEIRAO PRETO" },
  "351040": { nome: "Capivari",                  gve: "PIRACICABA" },
  "351050": { nome: "Caraguatatuba",             gve: "CARAGUATATUBA" },
  "351060": { nome: "Carapicuíba",               gve: "OSASCO" },
  "351070": { nome: "Cardoso",                   gve: "SAO JOSE DO RIO PRETO" },
  "351080": { nome: "Casa Branca",               gve: "SAO JOAO DA BOA VISTA" },
  "351100": { nome: "Castilho",                  gve: "ARACATUBA" },
  "351110": { nome: "Catanduva",                 gve: "SAO JOSE DO RIO PRETO" },
  "351170": { nome: "Charqueada",                gve: "PIRACICABA" },
  "351190": { nome: "Clementina",                gve: "ARACATUBA" },
  "351200": { nome: "Colina",                    gve: "BARRETOS" },
  "351210": { nome: "Colômbia",                  gve: "BARRETOS" },
  "351220": { nome: "Conchal",                   gve: "SAO JOAO DA BOA VISTA" },
  "351240": { nome: "Cordeirópolis",             gve: "PIRACICABA" },
  "351270": { nome: "Corumbataí",                gve: "PIRACICABA" },
  "351290": { nome: "Cosmorama",                 gve: "SAO JOSE DO RIO PRETO" },
  "351300": { nome: "Cotia",                     gve: "OSASCO" },
  "351310": { nome: "Cravinhos",                 gve: "RIBEIRAO PRETO" },
  "351330": { nome: "Cruzália",                  gve: "ASSIS" },
  "351350": { nome: "Cubatão",                   gve: "SANTOS" },
  "351370": { nome: "Descalvado",                gve: "ARARAQUARA" },
  "351380": { nome: "Diadema",                   gve: "SANTO ANDRE" },
  "351385": { nome: "Dirce Reis",                gve: "JALES" },
  "351390": { nome: "Divinolândia",              gve: "SAO JOAO DA BOA VISTA" },
  "351420": { nome: "Dolcinópolis",              gve: "JALES" },
  "351460": { nome: "Dumont",                    gve: "RIBEIRAO PRETO" },
  "351470": { nome: "Echaporã",                  gve: "MARILIA" },
  "351480": { nome: "Eldorado",                  gve: "REGISTRO" },
  "351490": { nome: "Elias Fausto",              gve: "CAMPINAS" },
  "351495": { nome: "Embaúba",                   gve: "SAO JOSE DO RIO PRETO" },
  "351500": { nome: "Embu das Artes",            gve: "OSASCO" },
  "351510": { nome: "Embu-Guaçu",               gve: "OSASCO" },
  "351515": { nome: "Engenheiro Coelho",         gve: "CAMPINAS" },
  "351518": { nome: "Espírito Santo do Pinhal",  gve: "SAO JOAO DA BOA VISTA" },
  "351520": { nome: "Estrela d'Oeste",           gve: "JALES" },
  "351535": { nome: "Euclides da Cunha Paulista", gve: "PRESIDENTE VENCESLAU" },
  "351540": { nome: "Fartura",                   gve: "OURINHOS" },
  "351550": { nome: "Fernandópolis",             gve: "JALES" },
  "351560": { nome: "Fernando Prestes",          gve: "SAO JOSE DO RIO PRETO" },
  "351565": { nome: "Fernão",                    gve: "BAURU" },
  "351570": { nome: "Ferraz de Vasconcelos",     gve: "MOGI DAS CRUZES" },
  "351580": { nome: "Flora Rica",                gve: "JALES" },
  "351590": { nome: "Floreal",                   gve: "SAO JOSE DO RIO PRETO" },
  "351600": { nome: "Flórida Paulista",          gve: "MARILIA" },
  "351630": { nome: "Francisco Morato",          gve: "FRANCO DA ROCHA" },
  "351640": { nome: "Franco da Rocha",           gve: "FRANCO DA ROCHA" },
  "351650": { nome: "Gabriel Monteiro",          gve: "ARACATUBA" },
  "351660": { nome: "Gália",                     gve: "MARILIA" },
  "351670": { nome: "Garça",                     gve: "MARILIA" },
  "351680": { nome: "Gastão Vidigal",            gve: "ARACATUBA" },
  "351685": { nome: "Gavião Peixoto",            gve: "ARARAQUARA" },
  "351690": { nome: "General Salgado",           gve: "ARACATUBA" },
  "351730": { nome: "Guaimbê",                   gve: "MARILIA" },
  "351740": { nome: "Guaíra",                    gve: "BARRETOS" },
  "351750": { nome: "Guapiaçu",                  gve: "SAO JOSE DO RIO PRETO" },
  "351770": { nome: "Guará",                     gve: "RIBEIRAO PRETO" },
  "351780": { nome: "Guaraçaí",                  gve: "ARACATUBA" },
  "351790": { nome: "Guaraci",                   gve: "BARRETOS" },
  "351800": { nome: "Guarani d'Oeste",           gve: "JALES" },
  "351810": { nome: "Guarantã",                  gve: "MARILIA" },
  "351830": { nome: "Guararema",                 gve: "MOGI DAS CRUZES" },
  "351840": { nome: "Guaratinguetá",             gve: "TAUBATE" },
  "351870": { nome: "Guarujá",                   gve: "SANTOS" },
  "351880": { nome: "Guarulhos",                 gve: "FRANCO DA ROCHA" },
  "351900": { nome: "Herculândia",               gve: "MARILIA" },
  "351920": { nome: "Iacri",                     gve: "MARILIA" },
  "351930": { nome: "Ibaté",                     gve: "ARARAQUARA" },
  "351940": { nome: "Ibirá",                     gve: "SAO JOSE DO RIO PRETO" },
  "351980": { nome: "Icém",                      gve: "SAO JOSE DO RIO PRETO" },
  "352030": { nome: "Iguape",                    gve: "REGISTRO" },
  "352042": { nome: "Ilha Comprida",             gve: "REGISTRO" },
  "352070": { nome: "Indiaporã",                 gve: "JALES" },
  "352080": { nome: "Inúbia Paulista",           gve: "MARILIA" },
  "352110": { nome: "Ipeúna",                    gve: "PIRACICABA" },
  "352115": { nome: "Ipiguá",                    gve: "SAO JOSE DO RIO PRETO" },
  "352120": { nome: "Iporanga",                  gve: "REGISTRO" },
  "352130": { nome: "Ipuã",                      gve: "RIBEIRAO PRETO" },
  "352140": { nome: "Iracemápolis",              gve: "PIRACICABA" },
  "352150": { nome: "Irapuã",                    gve: "SAO JOSE DO RIO PRETO" },
  "352170": { nome: "Itaberá",                   gve: "ITAPEVA" },
  "352190": { nome: "Itajobi",                   gve: "SAO JOSE DO RIO PRETO" },
  "352210": { nome: "Itanhaém",                  gve: "SANTOS" },
  "352215": { nome: "Itaoca",                    gve: "REGISTRO" },
  "352220": { nome: "Itapecerica da Serra",      gve: "OSASCO" },
  "352240": { nome: "Itapeva",                   gve: "ITAPEVA" },
  "352250": { nome: "Itapevi",                   gve: "OSASCO" },
  "352260": { nome: "Itapira",                   gve: "SAO JOAO DA BOA VISTA" },
  "352265": { nome: "Itapirapuã Paulista",       gve: "ITAPEVA" },
  "352280": { nome: "Itaporanga",                gve: "ITAPEVA" },
  "352310": { nome: "Itaquaquecetuba",           gve: "MOGI DAS CRUZES" },
  "352320": { nome: "Itararé",                   gve: "ITAPEVA" },
  "352330": { nome: "Itariri",                   gve: "REGISTRO" },
  "352340": { nome: "Itatiba",                   gve: "CAMPINAS" },
  "352360": { nome: "Itirapina",                 gve: "ARARAQUARA" },
  "352380": { nome: "Itobi",                     gve: "SAO JOAO DA BOA VISTA" },
  "352390": { nome: "Itu",                       gve: "SOROCABA" },
  "352420": { nome: "Jaborandi",                 gve: "BARRETOS" },
  "352440": { nome: "Jacareí",                   gve: "SAO JOSE DOS CAMPOS" },
  "352460": { nome: "Jacupiranga",               gve: "REGISTRO" },
  "352480": { nome: "Jales",                     gve: "JALES" },
  "352500": { nome: "Jandira",                   gve: "OSASCO" },
  "352530": { nome: "Jaú",                       gve: "BAURU" },
  "352570": { nome: "José Bonifácio",            gve: "SAO JOSE DO RIO PRETO" },
  "352580": { nome: "Júlio Mesquita",            gve: "MARILIA" },
  "352585": { nome: "Jumirim",                   gve: "SOROCABA" },
  "352590": { nome: "Jundiaí",                   gve: "CAMPINAS" },
  "352610": { nome: "Juquiá",                    gve: "REGISTRO" },
  "352620": { nome: "Juquitiba",                 gve: "REGISTRO" },
  "352630": { nome: "Lagoinha",                  gve: "TAUBATE" },
  "352660": { nome: "Lavrinhas",                 gve: "TAUBATE" },
  "352670": { nome: "Leme",                      gve: "PIRACICABA" },
  "352690": { nome: "Limeira",                   gve: "PIRACICABA" },
  "352710": { nome: "Lins",                      gve: "BAURU" },
  "352720": { nome: "Lorena",                    gve: "TAUBATE" },
  "352740": { nome: "Lucélia",                   gve: "MARILIA" },
  "352750": { nome: "Lucianópolis",              gve: "BAURU" },
  "352760": { nome: "Luís Antônio",              gve: "RIBEIRAO PRETO" },
  "352780": { nome: "Lupércio",                  gve: "MARILIA" },
  "352790": { nome: "Lutécia",                   gve: "ASSIS" },
  "352800": { nome: "Macatuba",                  gve: "BAURU" },
  "352810": { nome: "Macaubal",                  gve: "SAO JOSE DO RIO PRETO" },
  "352820": { nome: "Macedônia",                 gve: "JALES" },
  "352830": { nome: "Magda",                     gve: "SAO JOSE DO RIO PRETO" },
  "352850": { nome: "Mairiporã",                 gve: "FRANCO DA ROCHA" },
  "352870": { nome: "Marabá Paulista",           gve: "PRESIDENTE VENCESLAU" },
  "352885": { nome: "Marapoama",                 gve: "SAO JOSE DO RIO PRETO" },
  "352890": { nome: "Mariápolis",                gve: "MARILIA" },
  "352900": { nome: "Marília",                   gve: "MARILIA" },
  "352910": { nome: "Marinópolis",               gve: "JALES" },
  "352920": { nome: "Martinópolis",              gve: "PRESIDENTE PRUDENTE" },
  "352930": { nome: "Matão",                     gve: "ARARAQUARA" },
  "352940": { nome: "Mauá",                      gve: "SANTO ANDRE" },
  "352950": { nome: "Mendonça",                  gve: "SAO JOSE DO RIO PRETO" },
  "352960": { nome: "Meridiano",                 gve: "SAO JOSE DO RIO PRETO" },
  "352965": { nome: "Mesópolis",                 gve: "JALES" },
  "352990": { nome: "Miracatu",                  gve: "REGISTRO" },
  "353000": { nome: "Mira Estrela",              gve: "JALES" },
  "353010": { nome: "Mirandópolis",              gve: "ARACATUBA" },
  "353030": { nome: "Mirassol",                  gve: "SAO JOSE DO RIO PRETO" },
  "353050": { nome: "Mococa",                    gve: "SAO JOAO DA BOA VISTA" },
  "353060": { nome: "Mogi das Cruzes",           gve: "MOGI DAS CRUZES" },
  "353070": { nome: "Mogi Guaçu",               gve: "SAO JOAO DA BOA VISTA" },
  "353080": { nome: "Mogi Mirim",                gve: "SAO JOAO DA BOA VISTA" },
  "353090": { nome: "Mombuca",                   gve: "PIRACICABA" },
  "353100": { nome: "Monções",                   gve: "SAO JOSE DO RIO PRETO" },
  "353110": { nome: "Mongaguá",                  gve: "SANTOS" },
  "353130": { nome: "Monte Alto",                gve: "BARRETOS" },
  "353140": { nome: "Monte Aprazível",           gve: "SAO JOSE DO RIO PRETO" },
  "353150": { nome: "Monte Azul Paulista",       gve: "BARRETOS" },
  "353160": { nome: "Monte Castelo",             gve: "JALES" },
  "353170": { nome: "Monteiro Lobato",           gve: "SAO JOSE DOS CAMPOS" },
  "353205": { nome: "Motuca",                    gve: "ARARAQUARA" },
  "353220": { nome: "Narandiba",                 gve: "PRESIDENTE PRUDENTE" },
  "353230": { nome: "Natividade da Serra",       gve: "TAUBATE" },
  "353250": { nome: "Neves Paulista",            gve: "SAO JOSE DO RIO PRETO" },
  "353260": { nome: "Nhandeara",                 gve: "ARACATUBA" },
  "353282": { nome: "Nova Campina",              gve: "ITAPEVA" },
  "353284": { nome: "Nova Canaã Paulista",       gve: "JALES" },
  "353286": { nome: "Nova Castilho",             gve: "ARACATUBA" },
  "353290": { nome: "Nova Europa",               gve: "ARARAQUARA" },
  "353300": { nome: "Nova Granada",              gve: "SAO JOSE DO RIO PRETO" },
  "353350": { nome: "Novo Horizonte",            gve: "SAO JOSE DO RIO PRETO" },
  "353370": { nome: "Ocauçu",                    gve: "MARILIA" },
  "353390": { nome: "Olímpia",                   gve: "SAO JOSE DO RIO PRETO" },
  "353400": { nome: "Onda Verde",                gve: "SAO JOSE DO RIO PRETO" },
  "353410": { nome: "Oriente",                   gve: "MARILIA" },
  "353420": { nome: "Orindiúva",                 gve: "SAO JOSE DO RIO PRETO" },
  "353440": { nome: "Osasco",                    gve: "OSASCO" },
  "353450": { nome: "Oscar Bressane",            gve: "MARILIA" },
  "353460": { nome: "Osvaldo Cruz",              gve: "MARILIA" },
  "353470": { nome: "Ourinhos",                  gve: "OURINHOS" },
  "353475": { nome: "Ouroeste",                  gve: "JALES" },
  "353490": { nome: "Pacaembu",                  gve: "MARILIA" },
  "353500": { nome: "Palestina",                 gve: "SAO JOSE DO RIO PRETO" },
  "353510": { nome: "Palmares Paulista",         gve: "SAO JOSE DO RIO PRETO" },
  "353520": { nome: "Palmeira d'Oeste",          gve: "JALES" },
  "353550": { nome: "Paraguaçu Paulista",        gve: "ASSIS" },
  "353560": { nome: "Paraibuna",                 gve: "SAO JOSE DOS CAMPOS" },
  "353570": { nome: "Paraíso",                   gve: "SAO JOSE DO RIO PRETO" },
  "353590": { nome: "Paranapuã",                 gve: "JALES" },
  "353600": { nome: "Parapuã",                   gve: "MARILIA" },
  "353620": { nome: "Pariquera-Açu",             gve: "REGISTRO" },
  "353625": { nome: "Parisi",                    gve: "JALES" },
  "353650": { nome: "Paulínia",                  gve: "CAMPINAS" },
  "353657": { nome: "Paulistânia",               gve: "BAURU" },
  "353660": { nome: "Paulo de Faria",            gve: "SAO JOSE DO RIO PRETO" },
  "353690": { nome: "Pedranópolis",              gve: "JALES" },
  "353715": { nome: "Pedrinhas Paulista",        gve: "ASSIS" },
  "353720": { nome: "Pedro de Toledo",           gve: "REGISTRO" },
  "353740": { nome: "Pereira Barreto",           gve: "ARACATUBA" },
  "353760": { nome: "Peruíbe",                   gve: "SANTOS" },
  "353780": { nome: "Piedade",                   gve: "SOROCABA" },
  "353810": { nome: "Pindorama",                 gve: "SAO JOSE DO RIO PRETO" },
  "353830": { nome: "Piquerobi",                 gve: "PRESIDENTE PRUDENTE" },
  "353850": { nome: "Piquete",                   gve: "TAUBATE" },
  "353870": { nome: "Piracicaba",                gve: "PIRACICABA" },
  "353890": { nome: "Pirajuí",                   gve: "BAURU" },
  "353900": { nome: "Pirangi",                   gve: "SAO JOSE DO RIO PRETO" },
  "353910": { nome: "Pirapora do Bom Jesus",     gve: "OSASCO" },
  "353920": { nome: "Pirapozinho",               gve: "PRESIDENTE PRUDENTE" },
  "353950": { nome: "Pitangueiras",              gve: "RIBEIRAO PRETO" },
  "353960": { nome: "Planalto",                  gve: "SAO JOSE DO RIO PRETO" },
  "353970": { nome: "Platina",                   gve: "ASSIS" },
  "353980": { nome: "Poá",                       gve: "MOGI DAS CRUZES" },
  "353990": { nome: "Poloni",                    gve: "SAO JOSE DO RIO PRETO" },
  "354000": { nome: "Pompéia",                   gve: "MARILIA" },
  "354025": { nome: "Pontalinda",                gve: "JALES" },
  "354030": { nome: "Pontes Gestal",             gve: "SAO JOSE DO RIO PRETO" },
  "354040": { nome: "Populina",                  gve: "JALES" },
  "354050": { nome: "Porangaba",                 gve: "SOROCABA" },
  "354080": { nome: "Potirendaba",               gve: "SAO JOSE DO RIO PRETO" },
  "354085": { nome: "Pracinha",                  gve: "MARILIA" },
  "354090": { nome: "Pradópolis",                gve: "RIBEIRAO PRETO" },
  "354100": { nome: "Praia Grande",              gve: "SANTOS" },
  "354140": { nome: "Presidente Prudente",       gve: "PRESIDENTE PRUDENTE" },
  "354165": { nome: "Quadra",                    gve: "SOROCABA" },
  "354180": { nome: "Queiroz",                   gve: "MARILIA" },
  "354200": { nome: "Quintana",                  gve: "MARILIA" },
  "354210": { nome: "Rafard",                    gve: "PIRACICABA" },
  "354240": { nome: "Regente Feijó",             gve: "PRESIDENTE PRUDENTE" },
  "354260": { nome: "Registro",                  gve: "REGISTRO" },
  "354280": { nome: "Ribeira",                   gve: "ITAPEVA" },
  "354300": { nome: "Ribeirão Branco",           gve: "ITAPEVA" },
  "354310": { nome: "Ribeirão Corrente",         gve: "FRANCA" },
  "354323": { nome: "Ribeirão dos Índios",       gve: "PRESIDENTE VENCESLAU" },
  "354330": { nome: "Ribeirão Pires",            gve: "SANTO ANDRE" },
  "354340": { nome: "Ribeirão Preto",            gve: "RIBEIRAO PRETO" },
  "354350": { nome: "Riversul",                  gve: "ITAPEVA" },
  "354370": { nome: "Rincão",                    gve: "ARARAQUARA" },
  "354380": { nome: "Rinópolis",                 gve: "MARILIA" },
  "354390": { nome: "Rio Claro",                 gve: "PIRACICABA" },
  "354400": { nome: "Rio das Pedras",            gve: "PIRACICABA" },
  "354410": { nome: "Rio Grande da Serra",       gve: "SANTO ANDRE" },
  "354420": { nome: "Riolândia",                 gve: "JALES" },
  "354425": { nome: "Rosana",                    gve: "PRESIDENTE VENCESLAU" },
  "354450": { nome: "Rubinéia",                  gve: "JALES" },
  "354470": { nome: "Sagres",                    gve: "MARILIA" },
  "354480": { nome: "Sales",                     gve: "SAO JOSE DO RIO PRETO" },
  "354500": { nome: "Salesópolis",               gve: "MOGI DAS CRUZES" },
  "354510": { nome: "Salmourão",                 gve: "MARILIA" },
  "354515": { nome: "Saltinho",                  gve: "PIRACICABA" },
  "354530": { nome: "Salto de Pirapora",         gve: "SOROCABA" },
  "354540": { nome: "Salto Grande",              gve: "OURINHOS" },
  "354560": { nome: "Santa Adélia",              gve: "SAO JOSE DO RIO PRETO" },
  "354570": { nome: "Santa Albertina",           gve: "JALES" },
  "354610": { nome: "Santa Clara d'Oeste",       gve: "JALES" },
  "354620": { nome: "Santa Cruz da Conceição",   gve: "PIRACICABA" },
  "354625": { nome: "Santa Cruz da Esperança",   gve: "RIBEIRAO PRETO" },
  "354630": { nome: "Santa Cruz das Palmeiras",  gve: "SAO JOAO DA BOA VISTA" },
  "354660": { nome: "Santa Fé do Sul",           gve: "JALES" },
  "354670": { nome: "Santa Gertrudes",           gve: "PIRACICABA" },
  "354700": { nome: "Santa Maria da Serra",      gve: "PIRACICABA" },
  "354710": { nome: "Santa Mercedes",            gve: "PRESIDENTE VENCESLAU" },
  "354720": { nome: "Santana da Ponte Pensa",    gve: "JALES" },
  "354730": { nome: "Santana de Parnaíba",       gve: "OSASCO" },
  "354740": { nome: "Santa Rita d'Oeste",        gve: "JALES" },
  "354765": { nome: "Santa Salete",              gve: "JALES" },
  "354770": { nome: "Santo Anastácio",           gve: "PRESIDENTE PRUDENTE" },
  "354780": { nome: "Santo André",               gve: "SANTO ANDRE" },
  "354790": { nome: "Santo Antônio da Alegria",  gve: "RIBEIRAO PRETO" },
  "354810": { nome: "Santo Antônio do Jardim",   gve: "SAO JOAO DA BOA VISTA" },
  "354830": { nome: "Santo Expedito",            gve: "PRESIDENTE PRUDENTE" },
  "354840": { nome: "Santópolis do Aguapeí",     gve: "ARACATUBA" },
  "354850": { nome: "Santos",                    gve: "SANTOS" },
  "354880": { nome: "São Caetano do Sul",        gve: "SANTO ANDRE" },
  "354890": { nome: "São Carlos",                gve: "ARARAQUARA" },
  "354900": { nome: "São Francisco",             gve: "JALES" },
  "354910": { nome: "São João da Boa Vista",     gve: "SAO JOAO DA BOA VISTA" },
  "354920": { nome: "São João das Duas Pontes",  gve: "JALES" },
  "354925": { nome: "São João de Iracema",       gve: "JALES" },
  "354930": { nome: "São João do Pau d'Alho",    gve: "JALES" },
  "354950": { nome: "São José da Bela Vista",    gve: "FRANCA" },
  "354970": { nome: "São José do Rio Pardo",     gve: "SAO JOAO DA BOA VISTA" },
  "354980": { nome: "São José do Rio Preto",     gve: "SAO JOSE DO RIO PRETO" },
  "354990": { nome: "São José dos Campos",       gve: "SAO JOSE DOS CAMPOS" },
  "354995": { nome: "São Lourenço da Serra",     gve: "REGISTRO" },
  "355030": { nome: "São Paulo",                 gve: "SAO PAULO" },
  "355040": { nome: "São Pedro",                 gve: "PIRACICABA" },
  "355070": { nome: "São Sebastião",             gve: "CARAGUATATUBA" },
  "355080": { nome: "São Sebastião da Grama",    gve: "SAO JOAO DA BOA VISTA" },
  "355100": { nome: "São Vicente",               gve: "SANTOS" },
  "355120": { nome: "Sarutaiá",                  gve: "OURINHOS" },
  "355130": { nome: "Sebastianópolis do Sul",    gve: "SAO JOSE DO RIO PRETO" },
  "355140": { nome: "Serra Azul",                gve: "RIBEIRAO PRETO" },
  "355150": { nome: "Serrana",                   gve: "RIBEIRAO PRETO" },
  "355190": { nome: "Severínia",                 gve: "BARRETOS" },
  "355200": { nome: "Silveiras",                 gve: "TAUBATE" },
  "355220": { nome: "Sorocaba",                  gve: "SOROCABA" },
  "355230": { nome: "Sud Mennucci",              gve: "ARACATUBA" },
  "355250": { nome: "Suzano",                    gve: "MOGI DAS CRUZES" },
  "355260": { nome: "Tabapuã",                   gve: "SAO JOSE DO RIO PRETO" },
  "355280": { nome: "Taboão da Serra",           gve: "OSASCO" },
  "355300": { nome: "Taguaí",                    gve: "OURINHOS" },
  "355310": { nome: "Taiaçu",                    gve: "RIBEIRAO PRETO" },
  "355320": { nome: "Taiúva",                    gve: "RIBEIRAO PRETO" },
  "355330": { nome: "Tambaú",                    gve: "SAO JOAO DA BOA VISTA" },
  "355340": { nome: "Tanabi",                    gve: "SAO JOSE DO RIO PRETO" },
  "355360": { nome: "Tapiratiba",                gve: "SAO JOAO DA BOA VISTA" },
  "355365": { nome: "Taquaral",                  gve: "ARARAQUARA" },
  "355370": { nome: "Taquaritinga",              gve: "SAO JOSE DO RIO PRETO" },
  "355380": { nome: "Taquarituba",               gve: "OURINHOS" },
  "355385": { nome: "Taquarivaí",                gve: "BOTUCATU" },
  "355410": { nome: "Taubaté",                   gve: "TAUBATE" },
  "355430": { nome: "Teodoro Sampaio",           gve: "PRESIDENTE VENCESLAU" },
  "355440": { nome: "Terra Roxa",                gve: "RIBEIRAO PRETO" },
  "355460": { nome: "Timburi",                   gve: "OURINHOS" },
  "355465": { nome: "Torre de Pedra",            gve: "BOTUCATU" },
  "355475": { nome: "Trabiju",                   gve: "ARARAQUARA" },
  "355490": { nome: "Três Fronteiras",           gve: "JALES" },
  "355500": { nome: "Tupã",                      gve: "MARILIA" },
  "355510": { nome: "Tupi Paulista",             gve: "MARILIA" },
  "355520": { nome: "Turiúba",                   gve: "ARACATUBA" },
  "355530": { nome: "Turmalina",                 gve: "JALES" },
  "355535": { nome: "Ubarana",                   gve: "SAO JOSE DO RIO PRETO" },
  "355550": { nome: "Ubirajara",                 gve: "BAURU" },
  "355560": { nome: "Uchoa",                     gve: "SAO JOSE DO RIO PRETO" },
  "355570": { nome: "União Paulista",            gve: "SAO JOSE DO RIO PRETO" },
  "355580": { nome: "Urânia",                    gve: "JALES" },
  "355590": { nome: "Uru",                       gve: "BAURU" },
  "355600": { nome: "Urupês",                    gve: "SAO JOSE DO RIO PRETO" },
  "355610": { nome: "Valentim Gentil",           gve: "SAO JOSE DO RIO PRETO" },
  "355640": { nome: "Vargem Grande do Sul",      gve: "SAO JOAO DA BOA VISTA" },
  "355645": { nome: "Vargem Grande Paulista",    gve: "OSASCO" },
  "355660": { nome: "Vera Cruz",                 gve: "BAURU" },
  "355680": { nome: "Viradouro",                 gve: "BARRETOS" },
  "355690": { nome: "Vista Alegre do Alto",      gve: "RIBEIRAO PRETO" },
  "355695": { nome: "Vitória Brasil",            gve: "JALES" },
  "355710": { nome: "Votuporanga",               gve: "SAO JOSE DO RIO PRETO" },
  "355720": { nome: "Chavantes",                 gve: "OURINHOS" },
  "355730": { nome: "Estiva Gerbi",              gve: "SAO JOAO DA BOA VISTA" },
};

/** Retorna nome e GVE do município pelo código IBGE 6 dígitos */
export function infoMunicipio(codigo: string | null | undefined): MunicipioInfo | null {
  if (!codigo) return null;
  const cod = String(codigo).trim().replace(/\D/g, "").padStart(6, "0");
  return MUNICIPIOS_SP[cod] ?? null;
}

/** Retorna apenas o nome do município (compatibilidade retroativa) */
export function nomeMunicipio(codigo: string | null | undefined): string {
  if (!codigo) return "Não informado";
  const info = infoMunicipio(codigo);
  return info?.nome ?? String(codigo).trim();
}

/** Retorna o GVE do município pelo código IBGE */
export function gvePorCodigo(codigo: string | null | undefined): string | null {
  if (!codigo) return null;
  return infoMunicipio(codigo)?.gve ?? null;
}
