-- Epidemiological alerts generated by the weekly cron job.
-- An alert is raised when a GVE shows >50% increase vs the 4-week moving average.
CREATE TABLE IF NOT EXISTS epidemiological_alerts (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  se_epidemiologica INT  NOT NULL,
  ano             INT  NOT NULL,
  gve             TEXT NOT NULL,
  cases_current   INT  NOT NULL,
  cases_avg       FLOAT NOT NULL,
  increase_pct    FLOAT NOT NULL,
  severity        TEXT NOT NULL CHECK (severity IN ('warning', 'critical')),
  acknowledged    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE epidemiological_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users read alerts"
  ON epidemiological_alerts FOR SELECT TO authenticated USING (true);

CREATE POLICY "Service role manages alerts"
  ON epidemiological_alerts FOR ALL TO service_role USING (true) WITH CHECK (true);
